runtime: go111

env_variables:
  GOOGLE_CLOUD_PROJECT: nobo-signaling

handlers:
- url: /.*
  script: _go_app
  secure: always

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 1m
